#!/usr/bin/env bash

set -eu

exec /usr/bin/spawn-fcgi \
	-n \
	-d /usr/local/share/mapserver \
	-a $FCGI_LISTEN_ADDRESS \
	-p $FCGI_LISTEN_PORT \
	-F $FCGI_NPROC \
	-b $FCGI_BACKLOG \
	-u $FCGI_UID \
	-g $FCGI_GID \
	/usr/bin/mapserv