FROM php:5.6.31-fpm

MAINTAINER Maxime HELIAS <maximehelias16@gmail.com>

# Add content for php
COPY . /usr/local/docker
RUN chmod -R 777 /usr/local/docker

# Update & Install
RUN apt-get update && \
	apt-get install -y wget \
		curl \
		libmemcached-dev \
		libz-dev \
		libpq-dev \
		libjpeg-dev \
		libpng12-dev \
		libfreetype6-dev \
		libssl-dev \
		libmcrypt-dev \
		php5-mapscript && \
	docker-php-ext-configure gd \
		--enable-gd-native-ttf \
		--with-jpeg-dir=/usr/include/ \
		--with-freetype-dir=/usr/include/freetype2 && \
	docker-php-ext-install -j$(nproc) \
		gd \
		mcrypt \
		mbstring \
		pdo_pgsql

ADD php.ini /usr/local/etc/php/conf.d/
ADD php-fpm.conf /usr/local/etc/php-fpm-custom.conf

# Add PHP MapScript
RUN cp /usr/lib/php5/20131226/php_mapscript.so /usr/local/lib/php/extensions/no-debug-non-zts-20131226/php_mapscript.so
RUN docker-php-ext-enable php_mapscript

#####################################
# xDebug:
#####################################

ARG INSTALL_XDEBUG=false

ENV HOST_IP = `/sbin/ip route | awk '/default/ { print $3}'`
COPY xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

RUN if [ ${INSTALL_XDEBUG} = true ]; then \
	pecl install xdebug && \
	docker-php-ext-enable xdebug && \
	echo "xdebug.remote_host="$HOST_IP >> /usr/local/etc/php/conf.d/xdebug.ini \
;fi	

#####################################
# Blackfire:
#####################################

#####################################
# PHP REDIS EXTENSION FOR PHP 5
#####################################

ARG INSTALL_PHPREDIS=false
RUN if [ ${INSTALL_PHPREDIS} = true ]; then \
    pecl install redis \
    &&  rm -rf /tmp/pear \
    &&  docker-php-ext-enable redis \
;fi

#####################################
# Opcache:
#####################################

#####################################
# Image optimizers:
#####################################

#####################################
# ImageMagick:
#####################################

#####################################
# Final:
#####################################

# Clean up
USER root
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN usermod -u 1000 www-data

WORKDIR /var/www

CMD ["php-fpm"]

EXPOSE 9000
